#config_version=4
mode:
    start_events: ball_starting
    priority: 100
    
slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        #color: e20005         
      - type: text
        text: Player(number)
        style: dmd_small
        y: 1
        x: 1
        anchor_x: left
        anchor_y: bottom
        #color: e20005         
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        style: dmd_small
        #color: e20005         